[config]
default_to_workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.glutin_alsa]
command = "cargo"
args =["build"]
dependencies = ["clean"]

[tasks.glutin_wasapi]
command = "cargo"
args =["build","--target=x86_64-pc-windows-gnu"]
dependencies = ["clean"]

[tasks.web]
command = "cargo"
args =["build","--target=wasm32-unknown-unknown"]
dependencies = ["clean"]

[tasks.sdl2]
command = "cargo"
args =["build","--no-default-features","--features=sdl2"]
dependencies = ["clean"]

[tasks.build]
dependencies = [
    "glutin_alsa",
    "glutin_wasapi",
    "web",
    "sdl2",
]