[package]
name = "fluffl-macros"
version = "0.0.4"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = { version = "1.0.91", features = ['full'] }
quote = "1.0.18"
